### ISSUE TITLE
dryrun=True not continuing due to unknown exception

### ISSUE THREAD

**Issue by xpertservice** [pibara/aioflureedb#4]
Code executed:
        flureeclient = aioflureedb.FlureeClient(privkey, authId, port=8080, dryrun=True)
        await flureeclient.health.ready()

results in:

############# GET ##############
url: http://localhost:8080/fdb/health
################################
OOPS:  'ready'
Elapse process time: 0 s
Elapse time: 0.006 s

Process finished with exit code 0

**Comment by pibara** [comment]
The dryrun functionality has gone too much out of sync with normal operations and has been removed in trunk. Will propagate in max 2 days to pypi.
